# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
# Audrey: disabled it as it take way too long to build the blog 
lsi: false
# Removes the upper limit for posts generated
limit_posts: 0

source: src
destination: dist
